# my_entrepreneur_platform/my_entrepreneur_platform/settings.py

"""
Django settings for my_entrepreneur_platform project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-goes-here-replace-this-in-production!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    # Our Project Apps:
    'channels',
    'chat',
    'notifications',
    'axes',
    'users',
    'startups',
    'projects', # Our projects application
    'content', 
    'social',
    'search',


    # --- Apps for 2FA (django-two-factor-auth) --- (TEMPORARILY COMMENTED OUT DUE TO COMPATIBILITY ISSUES)
    # 'django_otp',
    # 'django_otp.plugins.otp_totp',
    # 'two_factor',
    # --- End Apps for 2FA ---
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # For CORS headers, must be high up
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'my_entrepreneur_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_entrepreneur_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Django Channels Specific Settings ---

ASGI_APPLICATION = 'my_entrepreneur_platform.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# --- Django REST Framework settings ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# --- AXES settings for Rate Limiting ---
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCK_OUT_BY_IP = True
AXES_LOCK_OUT_BY_USER = True
AXES_IP_WHITELIST = ['127.0.0.1']

# --- CORS Settings (for Frontend Integration) ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # Default create-react-app development server
    "http://127.0.0.1:3000",   # Common alternative for localhost
]
CORS_ALLOW_CREDENTIALS = True

# --- 2FA Settings (django-two-factor-auth) --- (TEMPORARILY COMMENTED OUT DUE TO COMPATIBILITY ISSUES)
# LOGIN_URL = 'two_factor:login'
# LOGIN_REDIRECT_URL = '/'


# --- Celery Configuration ---
# Broker URL: Where Celery sends and receives messages (your Redis server)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # '0' means database 0 in Redis
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0' # Where Celery stores task results (optional, but good for tracking)
CELERY_ACCEPT_CONTENT = ['json'] # Data format for messages
CELERY_TASK_SERIALIZER = 'json' # Data format for tasks
CELERY_RESULT_SERIALIZER = 'json' # Data format for results
CELERY_TIMEZONE = 'UTC' # Use UTC consistently

